name: Create new d-compat branch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  ci:
    uses: discourse/.github/.github/workflows/create-d-compat-branch.yml@bee9ee78c8e6fd574a8496f415e08c6eb412d3df # v1
